from building import *

cwd     = GetCurrentDir()
src     = Glob('*.c') + Glob('*.cpp')
CPPPATH = [cwd]

group = DefineGroup('Protocol', src, depend = ['PKG_USING_FIRE_PID_CURVE'], CPPPATH = CPPPATH)

Return('group')
