from building import *

cwd     = GetCurrentDir()
src     = Glob('*.c') + Glob('*.cpp')
CPPPATH = [cwd]

group = DefineGroup('Protocol', src, depend = ['FIRE_PID_CURVE_USING_EXAMPLE'], CPPPATH = CPPPATH)

Return('group')
